// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/presentation/blocs/session_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/src/domain/entities/session.dart' as _i2;
import 'package:app/src/domain/repositories/session_repository.dart' as _i3;
import 'package:app/src/domain/usecases/media/sessions/commit_refine_in_session_usecase.dart'
    as _i10;
import 'package:app/src/domain/usecases/media/sessions/drop_asset_in_session_usecase.dart'
    as _i8;
import 'package:app/src/domain/usecases/media/sessions/finish_session_usecase.dart'
    as _i6;
import 'package:app/src/domain/usecases/media/sessions/keep_asset_in_session_usecase.dart'
    as _i7;
import 'package:app/src/domain/usecases/media/sessions/start_session_usecase.dart'
    as _i5;
import 'package:app/src/domain/usecases/media/sessions/undo_last_operation_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i3.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Session>> getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue: _i4.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i4.Future<List<_i2.Session>>);

  @override
  _i4.Future<_i2.Session?> getSessionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionById, [id]),
            returnValue: _i4.Future<_i2.Session?>.value(),
          )
          as _i4.Future<_i2.Session?>);

  @override
  _i4.Future<_i2.Session?> getActiveSession() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSession, []),
            returnValue: _i4.Future<_i2.Session?>.value(),
          )
          as _i4.Future<_i2.Session?>);

  @override
  _i4.Future<int> createSession(_i2.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> updateSession(_i2.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllSessions, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [StartSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartSessionUseCase extends _i1.Mock
    implements _i5.StartSessionUseCase {
  MockStartSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> execute({
    required int? year,
    required int? month,
    required bool? isWhiteListMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #year: year,
              #month: month,
              #isWhiteListMode: isWhiteListMode,
            }),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#execute, [], {
                  #year: year,
                  #month: month,
                  #isWhiteListMode: isWhiteListMode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);
}

/// A class which mocks [FinishSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinishSessionUseCase extends _i1.Mock
    implements _i6.FinishSessionUseCase {
  MockFinishSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> execute({required _i2.Session? session}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#session: session}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession({required int? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [KeepAssetInSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeepAssetInSessionUseCase extends _i1.Mock
    implements _i7.KeepAssetInSessionUseCase {
  MockKeepAssetInSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> execute({
    required _i2.Session? session,
    required bool? isWhiteListMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #session: session,
              #isWhiteListMode: isWhiteListMode,
            }),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#execute, [], {
                  #session: session,
                  #isWhiteListMode: isWhiteListMode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);
}

/// A class which mocks [DropAssetInSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDropAssetInSessionUseCase extends _i1.Mock
    implements _i8.DropAssetInSessionUseCase {
  MockDropAssetInSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> execute({
    required _i2.Session? session,
    required bool? isWhiteListMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #session: session,
              #isWhiteListMode: isWhiteListMode,
            }),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#execute, [], {
                  #session: session,
                  #isWhiteListMode: isWhiteListMode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);
}

/// A class which mocks [UndoLastOperationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUndoLastOperationUseCase extends _i1.Mock
    implements _i9.UndoLastOperationUseCase {
  MockUndoLastOperationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> execute({required _i2.Session? session}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#session: session}),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#execute, [], {#session: session}),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);
}

/// A class which mocks [CommitRefineInSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommitRefineInSessionUseCase extends _i1.Mock
    implements _i10.CommitRefineInSessionUseCase {
  MockCommitRefineInSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> execute({required _i2.Session? session}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#session: session}),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#execute, [], {#session: session}),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);
}
