// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/assets_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/src/models/asset.dart' as _i4;
import 'package:app/src/services/assets_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AssetsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetsService extends _i1.Mock implements _i2.AssetsService {
  MockAssetsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> deleteAssetsPerId({
    required List<String>? assetIds,
    required bool? isDry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAssetsPerId,
          [],
          {
            #assetIds: assetIds,
            #isDry: isDry,
          },
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<int> getAssetsCount() => (super.noSuchMethod(
        Invocation.method(
          #getAssetsCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Asset>> listAssets({required int? year}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAssets,
          [],
          {#year: year},
        ),
        returnValue: _i3.Future<List<_i4.Asset>>.value(<_i4.Asset>[]),
      ) as _i3.Future<List<_i4.Asset>>);
}
