// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/presentation/views/settings_list_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:app/src/domain/usecases/settings/load_settings_usecase.dart'
    as _i2;
import 'package:app/src/domain/usecases/settings/update_settings_usecase.dart'
    as _i3;
import 'package:app/src/presentation/features/settings/blocs/settings/settings_cubit.dart'
    as _i5;
import 'package:app/src/presentation/features/settings/blocs/settings/settings_state.dart'
    as _i4;
import 'package:flutter/material.dart' as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoadSettingsUseCase_0 extends _i1.SmartFake
    implements _i2.LoadSettingsUseCase {
  _FakeLoadSettingsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateSettingsUseCase_1 extends _i1.SmartFake
    implements _i3.UpdateSettingsUseCase {
  _FakeUpdateSettingsUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsState_2 extends _i1.SmartFake implements _i4.SettingsState {
  _FakeSettingsState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i5.SettingsCubit {
  MockSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoadSettingsUseCase get loadSettingsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#loadSettingsUseCase),
            returnValue: _FakeLoadSettingsUseCase_0(
              this,
              Invocation.getter(#loadSettingsUseCase),
            ),
          )
          as _i2.LoadSettingsUseCase);

  @override
  _i3.UpdateSettingsUseCase get updateSettingsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#updateSettingsUseCase),
            returnValue: _FakeUpdateSettingsUseCase_1(
              this,
              Invocation.getter(#updateSettingsUseCase),
            ),
          )
          as _i3.UpdateSettingsUseCase);

  @override
  _i4.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettingsState_2(this, Invocation.getter(#state)),
          )
          as _i4.SettingsState);

  @override
  _i6.Stream<_i4.SettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.SettingsState>.empty(),
          )
          as _i6.Stream<_i4.SettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTheme(_i7.ThemeMode? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#updateTheme, [themeMode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDebugFlag(bool? isDryRun) =>
      (super.noSuchMethod(
            Invocation.method(#updateDebugFlag, [isDryRun]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhotosAccess(bool? hasAccess) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotosAccess, [hasAccess]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markInAppReviewCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#markInAppReviewCompleted, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i4.SettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i4.SettingsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
