// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/presentation/views/years_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:app/src/domain/repositories/asset_repository.dart' as _i4;
import 'package:app/src/domain/usecases/media/delete_assets_usecase.dart'
    as _i3;
import 'package:app/src/domain/usecases/media/refresh_photos_usecase.dart'
    as _i2;
import 'package:app/src/presentation/features/media/blocs/media/media_bloc.dart'
    as _i6;
import 'package:app/src/presentation/features/media/blocs/media/media_event.dart'
    as _i8;
import 'package:app/src/presentation/features/media/blocs/media/media_state.dart'
    as _i5;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRefreshPhotosUseCase_0 extends _i1.SmartFake
    implements _i2.RefreshPhotosUseCase {
  _FakeRefreshPhotosUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteAssetsUseCase_1 extends _i1.SmartFake
    implements _i3.DeleteAssetsUseCase {
  _FakeDeleteAssetsUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssetRepository_2 extends _i1.SmartFake
    implements _i4.AssetRepository {
  _FakeAssetRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaState_3 extends _i1.SmartFake implements _i5.MediaState {
  _FakeMediaState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaBloc extends _i1.Mock implements _i6.MediaBloc {
  MockMediaBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RefreshPhotosUseCase get refreshPhotosUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#refreshPhotosUseCase),
            returnValue: _FakeRefreshPhotosUseCase_0(
              this,
              Invocation.getter(#refreshPhotosUseCase),
            ),
          )
          as _i2.RefreshPhotosUseCase);

  @override
  _i3.DeleteAssetsUseCase get deleteAssetsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAssetsUseCase),
            returnValue: _FakeDeleteAssetsUseCase_1(
              this,
              Invocation.getter(#deleteAssetsUseCase),
            ),
          )
          as _i3.DeleteAssetsUseCase);

  @override
  _i4.AssetRepository get assetRepository =>
      (super.noSuchMethod(
            Invocation.getter(#assetRepository),
            returnValue: _FakeAssetRepository_2(
              this,
              Invocation.getter(#assetRepository),
            ),
          )
          as _i4.AssetRepository);

  @override
  _i5.MediaState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMediaState_3(this, Invocation.getter(#state)),
          )
          as _i5.MediaState);

  @override
  _i7.Stream<_i5.MediaState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.MediaState>.empty(),
          )
          as _i7.Stream<_i5.MediaState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i8.MediaEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.MediaEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.MediaState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.MediaEvent>(
    _i9.EventHandler<E, _i5.MediaState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i8.MediaEvent, _i5.MediaState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i5.MediaState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
