// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/data/repositories/asset_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/src/data/datasources/asset_local_datasource.dart' as _i2;
import 'package:app/src/data/local/models/asset_entity.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AssetLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetLocalDataSource extends _i1.Mock
    implements _i2.AssetLocalDataSource {
  MockAssetLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AssetEntity>> getAllAssets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAssets, []),
            returnValue: _i3.Future<List<_i4.AssetEntity>>.value(
              <_i4.AssetEntity>[],
            ),
          )
          as _i3.Future<List<_i4.AssetEntity>>);

  @override
  _i3.Future<_i4.AssetEntity?> getAssetById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetById, [id]),
            returnValue: _i3.Future<_i4.AssetEntity?>.value(),
          )
          as _i3.Future<_i4.AssetEntity?>);

  @override
  _i3.Future<_i4.AssetEntity?> getAssetByAssetId(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetByAssetId, [assetId]),
            returnValue: _i3.Future<_i4.AssetEntity?>.value(),
          )
          as _i3.Future<_i4.AssetEntity?>);

  @override
  _i3.Future<List<_i4.AssetEntity>> getAssetsByYear(int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetsByYear, [year]),
            returnValue: _i3.Future<List<_i4.AssetEntity>>.value(
              <_i4.AssetEntity>[],
            ),
          )
          as _i3.Future<List<_i4.AssetEntity>>);

  @override
  _i3.Future<List<_i4.AssetEntity>> getAssetsByYearAndMonth(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetsByYearAndMonth, [year, month]),
            returnValue: _i3.Future<List<_i4.AssetEntity>>.value(
              <_i4.AssetEntity>[],
            ),
          )
          as _i3.Future<List<_i4.AssetEntity>>);

  @override
  _i3.Future<List<int>> addAssets(List<_i4.AssetEntity>? assets) =>
      (super.noSuchMethod(
            Invocation.method(#addAssets, [assets]),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<void> updateAssets(List<_i4.AssetEntity>? assets) =>
      (super.noSuchMethod(
            Invocation.method(#updateAssets, [assets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAssets(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssets, [ids]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAssetsByYear(int? year) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssetsByYear, [year]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAssetsByYearAndMonth(int? year, int? month) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssetsByYearAndMonth, [year, month]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> deleteAssetsFromDevice({
    required List<String>? assetIds,
    required bool? isDry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssetsFromDevice, [], {
              #assetIds: assetIds,
              #isDry: isDry,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<int> getDeviceAssetsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceAssetsCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.AssetEntity>> listDeviceAssets({required int? year}) =>
      (super.noSuchMethod(
            Invocation.method(#listDeviceAssets, [], {#year: year}),
            returnValue: _i3.Future<List<_i4.AssetEntity>>.value(
              <_i4.AssetEntity>[],
            ),
          )
          as _i3.Future<List<_i4.AssetEntity>>);

  @override
  _i3.Future<void> authorizePhotos() =>
      (super.noSuchMethod(
            Invocation.method(#authorizePhotos, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isPhotosAuthorized() =>
      (super.noSuchMethod(
            Invocation.method(#isPhotosAuthorized, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
