// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9TS_w8Ngp5wZDt1BdN9EpoXxt1lDc7HI',
    appId: '1:411067881386:web:c2b61771025084eca7bdd3',
    messagingSenderId: '411067881386',
    projectId: 'saissyapps-cuisine',
    authDomain: 'saissyapps-cuisine.firebaseapp.com',
    storageBucket: 'saissyapps-cuisine.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupqgXxXAg41xr9FVd1Nai9ScH-4bYGSU',
    appId: '1:411067881386:android:6b1447a7bf6f84e5a7bdd3',
    messagingSenderId: '411067881386',
    projectId: 'saissyapps-cuisine',
    storageBucket: 'saissyapps-cuisine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HzHP97BQqJ42WjI6-bou658i4CNgr3c',
    appId: '1:411067881386:ios:a2c89d87d7da2ceea7bdd3',
    messagingSenderId: '411067881386',
    projectId: 'saissyapps-cuisine',
    storageBucket: 'saissyapps-cuisine.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HzHP97BQqJ42WjI6-bou658i4CNgr3c',
    appId: '1:411067881386:ios:a2c89d87d7da2ceea7bdd3',
    messagingSenderId: '411067881386',
    projectId: 'saissyapps-cuisine',
    storageBucket: 'saissyapps-cuisine.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
